### ISSUE TITLE
Update PyArrow dependency to support Windows

### ISSUE THREAD

**Issue by iblocks-Xander** [autofitcloud/isitfit#6]
Due to an issue with PyArrow 0.14.1, the Windows wheels were removed from PyPi (as per https://issues.apache.org/jira/browse/ARROW-6765)

This means that `isitfit` currently can't be installed on Windows.

I think a simple dependency update to 0.15.0 should fix the issue!

**Comment by shadiakiki1986** [comment]
Wow, thanks for catching that! Will update it now and create a new release :)

**Comment by shadiakiki1986** [comment]
Release 0.9.1 is available on pypi now with the pyarrow upgrade you suggested. You could upgrade isitfit with `pip3 install --upgrade isitfit`. Let me know if this works out

**Comment by iblocks-Xander** [comment]
Installs fine now on my end.

**Comment by shadiakiki1986** [comment]
Hello @iblocks-Xander    It's been a few months since you first tried out isitfit. Since then, I've improved it a lot and it's at version 0.20 now. I'll be happy to get your feedback on the latest version. You could upgrade with `pip3 install --upgrade isitfit` and then run `isitfit cost analyze` to calculate the efficiency of your AWS account, followed by `isitfit cost optimize` to get recommendations on which EC2/RDS sizes better be changed. Have a nice day!
